# Generated by Django 5.0.7 on 2024-07-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contect',
            new_name='content',
        ),
    ]
